### ISSUE TITLE
Bug: Keybinding configuration is not accessible

### ISSUE THREAD

**Issue by nancikennedy** [MrMime71/Outfitter#13]
Keybindings for Outfitter are not showing up in the Options:Keybindings panel.

**Comment by nulian** [comment]
Will have a look in how to show it in the new options

**Comment by nulian** [comment]
Next version which should be released soon will have a fix for the keybindings they will be under Outfitter! added question mark because I couldn't use addon name for it and couldn't find a way to use translations for that.

**Comment by MrMime71** [comment]
thank you again Nulian
