### ISSUE TITLE
#4 Option size bug

### ISSUE THREAD

**Issue by Addonman** [MrMime71/Outfitter#14]
This issues is back. It was gone in your version for most of shadowlands but like 1 or 2 updates its back. 
By makeing size of toottip in tiptac i want it resizes Outfitter windows as well and they get smaller and smaller ,hard to read.

**Comment by Addonman** [comment]
I guess its issue with Outfitter own  modifed lib and line 112.
Can it be change into something that wouldnt set casceding windows to be smaller and smaller?

**Comment by nulian** [comment]
Will have a look in a bit in how to fix this nicely.

**Comment by frozn** [comment]
Created a pull request for this, see #16.

**Comment by Addonman** [comment]
10x for fix
