### ISSUE TITLE
Dragonflight fixes

### ISSUE THREAD

**Issue by nulian** [MrMime71/Outfitter#6]
Made some dragonflight fixes though didn't see this repo so did it on the original outfitter github need to update it for this one.
Got most features to work for PTR and for beta still fixing the tooltip mostly working except closing.

https://github.com/nulian/Outfitter

**Comment by nulian** [comment]
See that you merged it I'll have a look at making it also beta/dragonflight compatible at the moment I haven't updated the ToolTip api yet in the MR. Because it also needs to be backwards compatible.
On prepatch it should work fine outfitter.

**Comment by MrMime71** [comment]
i have just been testing it on beta.. on wed we'll see :-)
